name: integration tests

on:
  push:
    branches:
      - '*.x'
  pull_request:
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: "ubuntu-latest"
    continue-on-error: false
    strategy:
      matrix:
        dependencies:
          - "highest"
          - "lowest"
        laravel:
          - 13
          - 12
          - 11
          - 10
          - 9
        phpunit:
          - '*'
        include:
          - laravel: 13
            phpunit: '^13.0'
            php: 8.4
          - laravel: 13
            phpunit: '^12.5'
            php: 8.3
          - laravel: 12
            phpunit: '^13.0'
            php: 8.4
          - laravel: 12
            phpunit: '^12.0'
            php: 8.3
          - laravel: 11
            phpunit: '^12.0'
            php: 8.3
          - laravel: 13
            phpunit: '^11.0'
            php: 8.3
          - laravel: 12
            phpunit: '^11.0'
            php: 8.2
          - laravel: 11
            phpunit: '^10.0'
            php: 8.2
          - laravel: 10
            phpunit: '^10.0'
            php: 8.1
          - laravel: 9
            phpunit: '^9.0'
            php: '8.0'

    name: Laravel:${{ matrix.laravel }} / PHP:${{ matrix.php }} / PHPUnit:${{ matrix.phpunit && matrix.phpunit || '*' }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Set package version
        run: composer config version ${{ matrix.laravel >= 13 && '1.2.x-dev' || '1.1.x-dev' }}

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=laravel/framework:^${{ matrix.laravel }} --with=phpunit/phpunit:${{ matrix.phpunit }}"

      - name: Installed dependencies
        run: composer show -D

      - name: Update PHPUnit Configuration
        run: |
          vendor/bin/phpunit --migrate-configuration
        if: matrix.php >= 8.1

      - name: Execute tests
        run: |
          vendor/bin/phpunit --no-coverage --no-configuration --dont-report-useless-tests --bootstrap vendor/autoload.php --color tests

  phpunit-tests:
    runs-on: "ubuntu-latest"
    continue-on-error: false
    strategy:
      matrix:
        dependencies:
          - "highest"
          - "lowest"
        phpunit:
          - '^12.0'
          - '^11.0'
          - '^10.0'
          - '^9.6'
        include:
          - phpunit: '^13.0'
            php: 8.3
          - phpunit: '^12.0'
            php: 8.3
          - phpunit: '^11.0'
            php: 8.2
          - phpunit: '^10.0'
            php: 8.1
          - phpunit: '^9.6'
            php: '8.0'

    name: PHPUnit:${{ matrix.phpunit }} / PHP:${{ matrix.php }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Set package version
        run: composer config version "1.x-dev"

      - name: Install dependencies
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:${{ matrix.phpunit }}"

      - name: Installed dependencies
        run: composer show -D

      - name: Execute tests
        run: |
          vendor/bin/phpunit --no-coverage --no-configuration --dont-report-useless-tests --bootstrap vendor/autoload.php --color tests
