name: tests

on:
  push:
    branches:
      - '*.x'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests-on-phpunit12:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - 8.5
          - 8.4
          - 8.3
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHPUnit:12 / PHP:${{ matrix.php }} / OS:${{ matrix.os }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Set package version
        run: composer config version "1.1.x-dev"

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:^12.0"

      - name: Installed dependencies
        run: composer show -D

      - name: Update PHPUnit Configuration
        run: |
          vendor/bin/phpunit --migrate-configuration

      - name: Execute tests
        run: |
          vendor/bin/phpunit

  tests-on-phpunit11:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - 8.4
          - 8.3
          - 8.2
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHPUnit:11 / PHP:${{ matrix.php }} / OS:${{ matrix.os }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Set package version
        run: composer config version "1.1.x-dev"

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:^11.0"

      - name: Installed dependencies
        run: composer show -D

      - name: Update PHPUnit Configuration
        run: |
          vendor/bin/phpunit --migrate-configuration

      - name: Execute tests
        run: |
          vendor/bin/phpunit

  tests-on-phpunit10:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - 8.1
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHPUnit:10 / PHP${{ matrix.php }} / OS:${{ matrix.os }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Set package version
        run: composer config version "1.1.x-dev"

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:^10.0"

      - name: Installed dependencies
        run: composer show -D

      - name: Update PHPUnit Configuration
        run: |
          vendor/bin/phpunit --migrate-configuration

      - name: Execute tests
        run: |
          vendor/bin/phpunit

  tests-on-phpunit9:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - '8.0'
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHPUnit:9 / PHP:${{ matrix.php }} / OS:${{ matrix.os }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Set package version
        run: composer config version "1.1.x-dev"

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=phpunit/phpunit:^9.6"

      - name: Installed dependencies
        run: composer show -D

      - name: Execute tests
        run: |
          vendor/bin/phpunit
